### PR TITLE
add note to payloadbodychecker doc

### PR DESCRIPTION
**Pull request by PatGod**
Add a note about the payloadbodychecker settings (related to issue #94)

### CODE REVIEW

**Review by rifiles — APPROVED** [review]

**Comment by PatGod** [comment]
Should this close issue #94? 

(As discussed, we will review separately the list of settings for this checker - should #94 remain open as a reminder for this @rifiles or can it be closed?)

**Comment by rifiles** [comment]
> Should this PR close issue #94?
> 
> (As discussed, we will review separately the list of settings for this checker - should #94 remain open as a reminder for this @rifiles or can it be closed?)

We probably won't be updating the checker docs again until the recipe gets merged into the Settings file, correct? If so, the doc changes can probably be included in that PR, so I think it's safe to close the issue.

**Comment by PatGod** [comment]
OK, will close #94 then. 

Note that the recipe file is not documented anywhere, and is obsolete with the settings file allowing checker settings, so the doc may not need to be updated any further. When we get to #95, a PR for #95 (if needed) will address this.

**Review by marina-p — APPROVED** [review]
:shipit:

**Pull request merged**
