### PR TITLE
Migrate to dotnet 5.0

### PR DESCRIPTION
**Pull request by stishkin**

### CODE REVIEW

**Review by marina-p — APPROVED** [review]
:shipit:

**Comment by marina-p** [comment]
@PatGod Good catch! yes, README needs to be updated.

---
In reply to: [784651096](https://github.com/microsoft/restler-fuzzer/pull/149#issuecomment-784651096) [](ancestors = 784651096)

**Comment by stishkin** [comment]
> Doesn't this change require updating the main README.md/documentation? Yet the main README.md is not updated in this PR. @marina-p @stishkin


Changed Readme.md (link to the installation package is the same)

**Comment by marina-p** [comment]
> [.NET core SDK 3.1](https://dotnet.microsoft.com/download/dotnet-core?utm_source=getdotnetcorecli&utm_medium=referral) or higher, for your appropriate OS.

@stishkin this place also can you please modify to 5.0

---
Refers to: README.md:62 in 88962ee. [](commit_id = 88962eee97a8dbb0dc4950fec3264d319634c744, deletion_comment = False)

**Review by marina-p — APPROVED** [review]
:shipit:

**Review by marina-p — APPROVED** [review]

**Pull request merged**
